spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3306/appointments_db
    username: root
    password: qaisar786
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 1045

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
