spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:mysql://localhost:3306/doctors_db
    username: root
    password: qaisar786
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 1044

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
